'use strict';
// Stage 3 - Self-Adaptive Automation: approved cases -> Playwright TypeScript reusing pages/demo-booking Page Objects, then a
// 5-run dry-run against the bundled demo-booking app (the Stage-equivalent environment) with the JSON reporter parsed per run.
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const { CONCEPTS } = require('../framework/ui-map');

const ROOT = path.join(__dirname, '..');
const FRAMEWORK = path.join(ROOT, 'framework');
const byId = Object.fromEntries(CONCEPTS.map((c) => [c.id, c]));
const q = (s) => String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'");

function specFor(c) {
  const body = c.steps.map((s) => {
    const code = s.ref ? byId[s.ref[0]].steps[s.ref[1]].code : [];
    return [`    await test.step('${s.n}. ${q(s.action)}', async () => {`, ...code.map((l) => `      ${l}`), '    });'].join('\n');
  });
  return [
    "import { test, expect } from '@playwright/test';",
    "import { SearchPage, ResultsPage, HotelPage, playbook } from '../pages/demo-booking';",
    '',
    `// Generated by Stage 3 from approved case ${c.id} (${c.epic} > ${c.story} > ${c.req}).`,
    '// Reuses the pages/demo-booking Page Objects (no raw selectors in specs); data comes from test-data/playbook.json.',
    `test.describe('${c.scenario}: ${q(c.scenarioTitle)}', () => {`,
    `  test('${c.id}: ${q(c.title)}', { tag: ['@${c.story}', '@${c.type.toLowerCase()}'] }, async ({ page }) => {`,
    '    const search = new SearchPage(page);',
    '    const results = new ResultsPage(page);',
    '    const hotel = new HotelPage(page);',
    '    const data = playbook();',
    ...body,
    '  });',
    '});',
    '',
  ].join('\n');
}

const CONFIG = `import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  timeout: 30_000,
  retries: 0,
  fullyParallel: true,
  workers: 2,
  outputDir: './test-results',
  reporter: [['json']],
  use: { baseURL: process.env.BASE_URL, headless: true, trace: 'retain-on-failure' },
});
`;

function prepareWorkspace(dir, cases) {
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(path.join(dir, 'tests'), { recursive: true });
  fs.cpSync(path.join(FRAMEWORK, 'pages'), path.join(dir, 'pages'), { recursive: true });
  fs.cpSync(path.join(FRAMEWORK, 'test-data'), path.join(dir, 'test-data'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'playwright.config.ts'), CONFIG);
  const nm = path.join(dir, 'node_modules');
  if (!fs.existsSync(nm)) fs.symlinkSync(path.join(ROOT, 'node_modules'), nm, 'dir');
  const files = [];
  for (const c of cases) {
    const file = `tests/${c.id}.spec.ts`;
    fs.writeFileSync(path.join(dir, file), specFor(c));
    files.push(file);
  }
  return files;
}

function flatten(report) {
  const out = [];
  const walk = (suite, file) => {
    for (const s of suite.specs || []) for (const t of s.tests || []) {
      const r = (t.results || [])[t.results.length - 1] || {};
      const err = (r.errors || [])[0] || r.error;
      out.push({ id: s.title.split(':')[0], title: s.title, file: s.file || file, status: r.status || t.status || 'unknown', durationMs: r.duration || 0, error: err ? String(err.message || '').replace(/\u001b\[[0-9;]*m/g, '').slice(0, 600) : null });
    }
    for (const c of suite.suites || []) walk(c, suite.file || file);
  };
  for (const s of report.suites || []) walk(s, s.file);
  return out;
}

function runOnce(dir, baseURL, n) {
  return new Promise((resolve) => {
    const out = path.join(dir, `report-run-${n}.json`);
    const started = Date.now();
    const child = spawn(path.join(ROOT, 'node_modules', '.bin', 'playwright'), ['test', '--config', 'playwright.config.ts'], {
      cwd: dir, env: { ...process.env, BASE_URL: baseURL, PLAYWRIGHT_JSON_OUTPUT_NAME: out, FORCE_COLOR: '0', CI: '1' },
    });
    let log = '';
    child.stdout.on('data', (d) => { log += d; });
    child.stderr.on('data', (d) => { log += d; });
    child.on('close', (code) => {
      let tests = [];
      try { tests = flatten(JSON.parse(fs.readFileSync(out, 'utf8'))); } catch { /* reporter did not write */ }
      resolve({ n, exitCode: code, startedAt: new Date(started).toISOString(), durationMs: Date.now() - started, tests, log: tests.length ? '' : log.slice(-2000) });
    });
  });
}

module.exports = { specFor, prepareWorkspace, runOnce, flatten };
